# fly.toml app configuration file generated for beachitt on 2025-05-23T17:45:15-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'beachitt'
primary_region = 'sjc'

[build]

[env]
  FLY_SCALE_TO_ZERO = '1h'
  NODE_ENV = 'production'
  PRIMARY_REGION = 'sjc'

[http_service]
  internal_port = 3000
  force_https = true
<<<<<<< HEAD
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
=======
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
>>>>>>> 2b8afbbdb5b425c5d97b1fc3737df981c9383eab
